version: 2

before:
  hooks:
    - go mod download

builds:
  - id: darwin
    main: ./main.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.version={{ .Version }}
    goos:
      - darwin
    goarch:
      - arm64
  - id: linux
    main: ./main.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.version={{ .Version }}
    goos:
      - linux
    goarch:
      - arm64

archives:
  - id: darwin
    ids:
      - darwin
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - LICENSE
      - README.md
      - completions/_tfstore
  - id: linux
    ids:
      - linux
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - LICENSE
      - README.md
      - completions/_tfstore

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - name: tfstore
    repository:
      owner: youyo
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    ids:
      - darwin
    homepage: "https://github.com/youyo/tfstore"
    description: "Create a Terraform remote-state backend (S3, native locking)."
    install: |
      bin.install "tfstore"
      zsh_completion.install "completions/_tfstore"
